import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createHash } from 'node:crypto';
import { cp, mkdir, readFile, rename, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { packager } from '@electron/packager';
import { extractFile, listPackage } from '@electron/asar';
import { readRuntimeLicenseManifest } from './runtime-licenses.mjs';

const run = promisify(execFile);
const root = process.cwd();
const release = resolve(root, 'release');
const stamp = new Date().toISOString().replace(/[:.]/g, '-');
const stage = join(release, `.staging-${stamp}`);
const metadata = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
const electronCache = join(root, 'artifacts', 'electron');
const electronZip = `electron-v${metadata.devDependencies.electron}-win32-x64.zip`;
let electronZipDir;
if (await stat(join(electronCache, electronZip)).catch(() => false)) {
  const checksums = await readFile(join(electronCache, 'SHASUMS256.txt'), 'utf8');
  const expected = checksums.split(/\r?\n/).map(line => line.trim().split(/\s+/)).find(parts => parts[1]?.replace(/^\*/, '') === electronZip)?.[0];
  const actual = createHash('sha256').update(await readFile(join(electronCache, electronZip))).digest('hex');
  if (!expected || actual !== expected) throw new Error('Electron cache does not match the official SHA-256 manifest.');
  electronZipDir = electronCache;
}
await mkdir(stage, { recursive: true });
// An explicit allowlist keeps local records, credentials and build tools out of the app.
await cp(join(root, 'dist'), join(stage, 'dist'), { recursive: true });
const desktopFiles = ['main.cjs', 'preload.cjs', 'knowledge-import-worker.cjs', 'native-paste.ps1', 'usb-serial.ps1', 'usb-channel.ps1', 'window-identity.ps1', 'cu-native.ps1'];
const licenseFiles = ['react', 'react-dom', 'lucide-react', '@fontsource-variable-dm-sans', '@fontsource-variable-noto-sans-sc'].map(name => `${name}.txt`);
const runtimeLicenses = await readRuntimeLicenseManifest(root);
await mkdir(join(stage, 'desktop-build', 'licenses'), { recursive: true });
for (const name of desktopFiles) await cp(join(root, 'desktop-build', name), join(stage, 'desktop-build', name));
await cp(join(root, 'desktop-build', 'firmware'), join(stage, 'desktop-build', 'firmware'), { recursive: true });
for (const name of licenseFiles) await cp(join(root, 'desktop-build', 'licenses', name), join(stage, 'desktop-build', 'licenses', name));
for (const name of runtimeLicenses.files) {
  const destination = join(stage, 'desktop-build', 'licenses', name);
  await mkdir(dirname(destination), { recursive: true });
  await cp(join(runtimeLicenses.directory, name), destination);
}
await writeFile(join(stage, 'package.json'), JSON.stringify({ name: 'flowdesk', productName: 'FlowDesk', version: metadata.version, description: metadata.description, main: 'desktop-build/main.cjs', author: 'FlowDesk' }, null, 2));
const archive = join(release, 'FlowDesk-win32-x64.zip');
// A fresh output directory also works when an older portable app is still open.
const softwareRelease = join(release, 'windows-software', stamp);
await mkdir(softwareRelease, { recursive: true });
console.log('Packaging only dist, explicitly listed desktop runtime files, licenses, and the runtime manifest.');
const [built] = await packager({ dir: stage, out: softwareRelease, name: 'FlowDesk', platform: 'win32', arch: 'x64', electronVersion: metadata.devDependencies.electron, electronZipDir, overwrite: false, asar: { unpack: '**/{*.ps1,knowledge-import-worker.cjs}' }, prune: false });
const executable = join(built, 'FlowDesk.exe');
await stat(executable);
await stat(join(built, 'resources', 'app.asar'));
const asarFile = join(built, 'resources', 'app.asar');
if (!extractFile(asarFile, join('dist', 'simulator.html')).length) throw new Error('Reply-mode simulator missing from the Windows package.');
if (listPackage(asarFile).some(file => /flowdesk-state|secrets|node_modules|\.tools/.test(file))) throw new Error('Development or private state found in package.');
await stat(join(built, 'resources', 'app.asar.unpacked', 'desktop-build', 'native-paste.ps1'));
await stat(join(built, 'resources', 'app.asar.unpacked', 'desktop-build', 'usb-serial.ps1'));
await stat(join(built, 'resources', 'app.asar.unpacked', 'desktop-build', 'cu-native.ps1'));
await stat(join(built, 'resources', 'app.asar.unpacked', 'desktop-build', 'usb-channel.ps1'));
if (!extractFile(asarFile, join('desktop-build', 'firmware', 'flowdesk_usb.uf2')).length) throw new Error('USB firmware missing from the Windows package.');
const smokeEnv = { ...process.env, FLOWDESK_SMOKE_DIR: join(release, `.smoke-${stamp}`) };
delete smokeEnv.ELECTRON_RUN_AS_NODE;
const smoke = await run(executable, ['--smoke-test'], { windowsHide: true, env: smokeEnv, timeout: 30000, maxBuffer: 500000 });
console.log(smoke.stdout.trim());
if (!smoke.stdout.includes('FlowDesk renderer loaded successfully.')) throw new Error('Packaged application did not report a successful renderer smoke test.');
const knowledgeSmoke = await run(executable, ['--knowledge-smoke-test'], { windowsHide: true, env: smokeEnv, timeout: 45000, maxBuffer: 500000 });
console.log(knowledgeSmoke.stdout.trim());
if (!knowledgeSmoke.stdout.includes('FlowDesk knowledge import smoke passed.')) throw new Error('Packaged knowledge import smoke did not pass.');
const usbSmoke = await run(executable, ['--usb-smoke-test'], { windowsHide: true, env: smokeEnv, timeout: 120000, maxBuffer: 500000 });
console.log(usbSmoke.stdout.trim());
if (!usbSmoke.stdout.includes('FlowDesk USB replies smoke passed.')) throw new Error('Packaged USB replies smoke did not pass.');
const computerUseSmokeEnv = { ...process.env, FLOWDESK_SMOKE_DIR: join(release, `.cu-smoke-${stamp}`) };
delete computerUseSmokeEnv.ELECTRON_RUN_AS_NODE;
const computerUseSmoke = await run(executable, ['--cu-smoke-test'], { windowsHide: true, env: computerUseSmokeEnv, timeout: 60_000, maxBuffer: 500000 });
console.log(computerUseSmoke.stdout.trim());
if (!computerUseSmoke.stdout.includes('FlowDesk Computer Use SDK smoke passed.')) throw new Error('Packaged application did not report a Computer Use SDK smoke pass.');
const geminiSmoke = await run(executable, ['--gemini-smoke-test'], { windowsHide: true, env: { ...computerUseSmokeEnv, FLOWDESK_SMOKE_DIR: join(release, `.gemini-smoke-${stamp}`) }, timeout: 180000, maxBuffer: 500000 });
console.log(geminiSmoke.stdout.trim());
if (!geminiSmoke.stdout.includes('FlowDesk Gemini native smoke passed.')) throw new Error('Packaged Gemini native smoke did not pass.');
const geminiRepliesSmoke = await run(executable, ['--gemini-replies-smoke-test'], { windowsHide: true, env: { ...computerUseSmokeEnv, FLOWDESK_SMOKE_DIR: join(release, `.gemini-replies-smoke-${stamp}`) }, timeout: 240000, maxBuffer: 500000 });
console.log(geminiRepliesSmoke.stdout.trim());
if (!geminiRepliesSmoke.stdout.includes('FlowDesk Gemini persistent replies smoke passed.')) throw new Error('Packaged Gemini persistent replies smoke did not pass.');
const repliesEnv = { ...process.env, FLOWDESK_SMOKE_DIR: join(release, `.replies-smoke-${stamp}`) };
delete repliesEnv.ELECTRON_RUN_AS_NODE;
const repliesSmoke = await run(executable, ['--replies-smoke-test'], { windowsHide: true, env: repliesEnv, timeout: 120000, maxBuffer: 500000 });
console.log(repliesSmoke.stdout.trim());
if (!repliesSmoke.stdout.includes('FlowDesk desktop replies smoke passed.')) throw new Error('Packaged persistent desktop replies did not pass.');
await cp(join(root, 'docs', '使用说明.txt'), join(built, '使用说明.txt'));
await cp(join(root, 'docs', '客户知识库适配指南.md'), join(built, '客户知识库适配指南.md'));
await cp(join(root, 'public', 'knowledge-template.csv'), join(built, 'knowledge-template.csv'));
await cp(join(root, 'public', 'knowledge-evaluation-template.csv'), join(built, 'knowledge-evaluation-template.csv'));
const packagedFirmware = extractFile(asarFile, join('desktop-build', 'firmware', 'flowdesk_usb.uf2'));
await writeFile(join(built, 'FlowDesk-Pico-RP2040.uf2'), packagedFirmware);
await writeFile(join(built, 'FlowDesk-Pico-RP2040.uf2.sha256'), `${createHash('sha256').update(packagedFirmware).digest('hex')}  FlowDesk-Pico-RP2040.uf2\n`);
await cp(join(root, 'docs', 'Pico-到货烧录与测试.md'), join(built, 'Pico-到货烧录与测试.md'));
const nextArchive = join(release, `.FlowDesk-${stamp}.zip`);
await run('powershell.exe', ['-NoProfile', '-NonInteractive', '-File', join(root, 'scripts', 'archive.ps1'), '-Source', resolve(built), '-Destination', nextArchive], { windowsHide: true, timeout: 300000 });
if (await stat(archive).catch(() => false)) await rename(archive, `${archive}.previous-${stamp}`);
await rename(nextArchive, archive);
const info = await stat(archive);
console.log(`Windows package verified: ${archive} (${(info.size / 1024 / 1024).toFixed(1)} MB)`);
