import { useState } from 'react';
import { Download, Search, Upload } from 'lucide-react';
import { parse } from 'csv-parse/browser/esm/sync';
import type { KnowledgeEvaluationResult, KnowledgeSearchResult } from '../shared/knowledge';
import type { PageProps } from './App';
import { Button, Field } from './components';
import { downloadJson } from './api';

type Case = { question: string; expectedTitle?: string };
const parsePasted = (value: string): Case[] => value.split('\n').map(line => line.trim()).filter(Boolean).map(line => { const [question, expectedTitle] = line.split(/\||\t/, 2).map(x => x.trim()); return { question, expectedTitle: expectedTitle || undefined }; }).filter(item => item.question);
export default function KnowledgeLab({ perform, busy, notify }: PageProps) {
  const [query, setQuery] = useState(''); const [scenario, setScenario] = useState('all'); const [result, setResult] = useState<KnowledgeSearchResult>(); const [cases, setCases] = useState(''); const [evaluation, setEvaluation] = useState<KnowledgeEvaluationResult>(); const [csvError, setCsvError] = useState('');
  const search = async () => { if (!query.trim()) return notify('请输入要检索的问题。', true); const response = await perform<KnowledgeSearchResult>('POST', '/knowledge/search', { query, scenario }); if (response) setResult(response); };
  const evaluate = async () => { const parsed = parsePasted(cases); if (!parsed.length) return notify('每行写一个问题，可用 | 或 Tab 分隔预期标题。', true); const response = await perform<KnowledgeEvaluationResult>('POST', '/knowledge/evaluate', { cases: parsed, scenario }); if (response) setEvaluation(response); };
  const readCsv = async (file?: File) => { setCsvError(''); if (!file) return; if (file.size > 1024 * 1024) return setCsvError('CSV 不能超过 1MB。'); try { const records = parse(await file.text(), { columns: true, skip_empty_lines: true, trim: true, bom: true }) as Array<Record<string, unknown>>; if (records.length > 100) throw new Error('CSV 最多 100 行。'); const keys = records.length ? Object.keys(records[0]) : []; if (!keys.includes('问题') || !keys.includes('预期命中标题')) throw new Error('CSV 必须包含“问题”和“预期命中标题”两列。'); const parsed = records.map(row => ({ question: String(row['问题'] || '').trim(), expectedTitle: String(row['预期命中标题'] || '').trim() || undefined })); if (parsed.some(row => !row.question)) throw new Error('CSV 每行都需要“问题”。'); setCases(parsed.map(row => `${row.question}|${row.expectedTitle || ''}`).join('\n')); notify(`已载入 ${parsed.length} 条 CSV 测试用例。`); } catch (error) { setCsvError(`CSV 解析失败：${(error as Error).message}`); } };
  return <section className="knowledge-lab"><div className="panel lab-card"><div className="panel-head"><div><h2><Search size={17} />检索演练</h2><p>离线关键词检索，显示命中的本地知识；这不是 AI 答复。</p></div></div><div className="lab-controls"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="例如：退款需要哪些条件？" onKeyDown={e => { if (e.key === 'Enter') void search(); }} /><select value={scenario} onChange={e => setScenario(e.target.value)}><option value="all">全部场景</option><option value="service">电商客服</option><option value="sales">私域销售</option><option value="community">社群运营</option><option value="recruitment">招聘沟通</option><option value="content">内容运营</option></select><Button busy={busy} onClick={() => void search()}>检索</Button></div>{result && <div className="search-hit-list"><p className="muted">{result.note}</p>{result.hits.map(hit => <article key={hit.id}><div><strong>{hit.title}</strong><small>来源：{hit.source || '手动录入'} · 分数 {hit.score} · 命中：{hit.matchedTerms.join('、') || '内容'}</small></div><p>{hit.content}</p><span>匹配字段：{hit.matchedFields.join('、')}</span></article>)}{!result.hits.length && <p className="muted">没有命中。默认只检索已审核且已启用的知识。</p>}</div>}</div><details className="panel evaluation-panel"><summary>批量演练与评估</summary><div className="evaluation-body"><Field label="测试用例" hint="每行：问题|预期标题，或从 Excel 复制两列 Tab 文本。预期标题留空表示应无命中。"><textarea rows={6} value={cases} onChange={e => setCases(e.target.value)} placeholder={'退款多久到账？|退款规则\n未知的测试问题|'} /></Field><div className="lab-actions"><a className="text-link" href="/knowledge-evaluation-template.csv" download>下载 CSV 模板</a><label className="btn btn-secondary file-button"><Upload size={15} />导入 CSV<input type="file" accept=".csv,text/csv" onChange={e => { void readCsv(e.target.files?.[0]); e.target.value = ''; }} /></label><Button busy={busy} onClick={() => void evaluate()}>运行批量演练</Button>{evaluation && <Button variant="secondary" onClick={() => downloadJson(evaluation, 'FlowDesk-知识库演练报告.json')}><Download size={15} />下载 JSON 报告</Button>}</div>{csvError && <p className="error-text">{csvError}</p>}{evaluation && <><p className="evaluation-summary">共 {evaluation.total} 条，检索到 {evaluation.matched} 条，通过 {evaluation.passed} 条。</p>{evaluation.results.filter(item => !item.passed).map((item, index) => <p className="evaluation-failure" key={`${item.query}-${index}`}>未通过：问题「{item.query}」；预期「{item.expectedTitle || '无命中'}」；实际「{item.hits[0]?.title || '无命中'}」。</p>)}</>}</div></details></section>;
}
