import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, Plus, Sparkles, Clock3, CheckCheck, ScanLine, BookOpen, ChevronRight, ArrowLeft, Copy, Archive, RotateCcw, ShieldCheck, FileText, Zap, MessageSquare, Send, ExternalLink, Save, Search, Check, Circle, Monitor } from 'lucide-react';
import type { CaptureResult, Task, TaskStatus, UsbStatus } from '../shared/types';
import type { PageProps } from './App';
import { Button, Empty, Field, Modal, PageHead, Status, formatTime, scenarios, statuses } from './components';
import { api, copyText, navigate } from './api';

export function Dashboard(props: PageProps) {
  const { state, newTask } = props;
  const active = state.tasks.filter(t => t.status !== 'archived');
  const review = active.filter(t => t.status === 'review');
  const done = active.filter(t => t.status === 'completed');
  return <><PageHead eyebrow="YOUR EVERYDAY, REIMAGINED" title={`${state.preferences.operatorName || '你好'}，让工作轻一点。`} description="在这里，把重复的沟通变成有条理的下一步。" actions={<Button onClick={newTask}><Plus size={17} />新建任务</Button>} />
    <section className="welcome-banner"><div className="welcome-copy"><span className="welcome-tag"><span />你的桌面 AI 工作伙伴</span><h2>你负责判断，<br />让助手接住繁琐。</h2><p>看懂窗口，连接业务知识，把每次回复<br className="desktop-break" />准备好，再由你决定下一步。</p><Button onClick={() => navigate('capture')}>选择一个工作窗口<ArrowUpRight size={17} /></Button><span className="welcome-note">单次截屏 · 人工审核 · 全程留痕</span></div><div className="welcome-visual" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="welcome-mini-card source-card"><span className="mini-icon"><MessageSquare size={19} /></span><div><b>新的客户咨询</b><small>等待你的下一次回应</small></div><span className="mini-unread" /></div><div className="welcome-mini-card agent-card"><div className="agent-glyph"><Sparkles size={23} /></div><strong>FlowDesk</strong><span>看 · 想 · 做</span><div className="mini-wave"><i /><i /><i /><i /><i /><i /><i /></div></div><div className="welcome-mini-card result-card"><ShieldCheck size={19} /><div><b>回复草稿已就绪</b><small>每一步，由你掌控</small></div><Check size={16} /></div><span className="visual-caption">工作流程示意</span></div></section>
    <div className="stats-grid">{[[active.length, '工作任务', ListIcon, '本地工作空间中的任务'], [review.length, '等待审核', Clock3, '需要你确认的回复'], [done.length, '已交接草稿', CheckCheck, '已复制或填入，非发送数'], [state.knowledge.filter(k => k.enabled).length, '可用知识', BookOpen, '为回复提供业务依据']].map(([value, label, Icon, hint]) => { const StatIcon = Icon as typeof Clock3; return <div className="stat-card" key={String(label)}><div><span>{String(label)}</span><StatIcon size={18} /></div><strong>{String(value).padStart(2, '0')}</strong><small>{String(hint)}</small></div>; })}</div>
    <div className="dashboard-columns"><section className="panel"><div className="panel-head"><div><h2>最近的任务 <span className="count-badge">{active.length}</span></h2><p>所有对话，都有下一步。</p></div><button className="text-link" onClick={() => navigate('tasks')}>查看全部<ArrowRight size={15} /></button></div><TaskRows tasks={[...active].sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, 5)} /></section><section className="panel getting-started"><div className="panel-head"><div><h2>从这里开始</h2><p>准备好你的工作助手。</p></div><Sparkles size={18} /></div>{[{ title: '把业务知识交给助手', detail: '产品信息、常见问题、服务规则', route: 'knowledge', done: state.knowledge.some(k => k.enabled) }, { title: '设定你的工作流程', detail: '让回复符合团队的表达方式', route: 'workflows', done: state.workflows.some(w => w.enabled) }, { title: '连接一个视觉模型', detail: '使用你自己的 API 与模型', route: 'settings', done: !!state.provider.model && state.provider.hasKey }].map((item, i) => <button key={item.route} className="onboarding-item" onClick={() => navigate(item.route)}><span className={item.done ? 'step-complete' : 'step-number'}>{item.done ? <Check size={15} /> : i + 1}</span><div><strong>{item.title}</strong><small>{item.detail}</small></div><ChevronRight size={16} /></button>)}<div className="demo-label"><FileText size={14} />初始数据为示例，可编辑或删除。</div></section></div>
  </>;
}
const ListIcon = FileText;

function TaskRows({ tasks }: { tasks: Task[] }) {
  return !tasks.length ? <Empty title="准备好开始第一项工作了吗？" detail="创建任务，或者选择一个窗口，助手会在这里等你。" /> : <div className="task-table-wrap"><table className="task-table"><thead><tr><th>任务</th><th>状态</th><th>更新时间</th><th><span className="sr-only">打开</span></th></tr></thead><tbody>{tasks.map(task => <tr key={task.id}><td><button className="task-name" onClick={() => navigate(`task/${task.id}`)}><span className={`task-icon scenario-${task.scenario}`}><MessageSquare size={17} /></span><span><strong>{task.title}</strong><small>{scenarios[task.scenario]}<span>·</span>{task.mode === 'demo' ? '离线演示' : '真实模型'}</small></span></button></td><td><Status status={task.status} /></td><td className="task-date">{formatTime(task.updatedAt)}</td><td><button className="icon-button" aria-label={`打开 ${task.title}`} onClick={() => navigate(`task/${task.id}`)}><ArrowUpRight size={17} /></button></td></tr>)}</tbody></table></div>;
}

export function Tasks({ state, newTask }: PageProps) {
  const [filter, setFilter] = useState<TaskStatus | 'all'>('all'); const [search, setSearch] = useState('');
  const tasks = state.tasks.filter(t => (filter === 'all' ? t.status !== 'archived' : t.status === filter) && `${t.title} ${t.input}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt));
  return <><PageHead title="任务中心" description="从一条咨询到一份审核过的回复，让每个任务有始有终。" actions={<Button onClick={newTask}><Plus size={17} />新建任务</Button>} /><section className="panel"><div className="list-toolbar"><div className="tabs" role="tablist" aria-label="任务状态筛选">{(['all', 'draft', 'review', 'approved', 'completed', 'archived'] as const).map(key => <button role="tab" aria-selected={filter === key} key={key} onClick={() => setFilter(key)} className={filter === key ? 'selected' : ''}>{key === 'all' ? '全部任务' : statuses[key]}<span>{state.tasks.filter(t => key === 'all' ? t.status !== 'archived' : t.status === key).length}</span></button>)}</div><div className="search-box compact"><Search size={16} /><input aria-label="筛选任务" value={search} placeholder="搜索任务…" onChange={e => setSearch(e.target.value)} /></div></div><TaskRows tasks={tasks} /><div className="table-footer">共 {tasks.length} 个任务<span>草稿交接不代表已向客户发送</span></div></section></>;
}

export function TaskDetail({ state, perform, busy, notify, taskId, capture }: PageProps & { taskId: string; capture?: CaptureResult }) {
  const task = state.tasks.find(t => t.id === taskId);
  const [input, setInput] = useState(task?.input || ''); const [reply, setReply] = useState(task?.reply || '');
  const [mode, setMode] = useState<'demo' | 'live'>(task?.mode || 'demo'); const [confirmLive, setConfirmLive] = useState(false); const [confirmPaste, setConfirmPaste] = useState(false); const [confirmArchive, setConfirmArchive] = useState(false); const [copyBusy, setCopyBusy] = useState(false); const [usbStatus, setUsbStatus] = useState<UsbStatus>();
  useEffect(() => { setInput(task?.input || ''); setReply(task?.reply || ''); }, [task?.id, task?.updatedAt]);
  useEffect(() => { if (!window.flowdesk?.usb) return; const read = () => void window.flowdesk!.usb.status().then(setUsbStatus).catch(() => setUsbStatus(undefined)); read(); const timer = window.setInterval(read, 2000); return () => window.clearInterval(timer); }, []);
  if (!task) return <Empty title="没有找到这个任务" detail="它可能已被备份恢复替换，或链接不正确。" action={<Button onClick={() => navigate('tasks')}>返回任务中心</Button>} />;
  const dirty = input !== task.input || reply !== task.reply;
  const workflow = state.workflows.find(w => w.id === task.workflowId);
  const readOnly = task.status === 'archived' || task.status === 'completed';
  const save = () => perform<Task>('PUT', `/tasks/${task.id}`, { input, reply }, '修改已保存，请重新审核');
  const generate = async () => {
    if (dirty && !await perform<Task>('PUT', `/tasks/${task.id}`, { input, reply })) return;
    const result = await perform<Task>('POST', `/tasks/${task.id}/generate`, { mode, ...(mode === 'live' && capture ? { image: capture.image } : {}) }, mode === 'demo' ? '离线示例草稿已生成，请审核' : '模型回复已生成，请审核');
    if (result) { setReply(result.reply); setInput(result.input); }
    setConfirmLive(false);
  };
  const handoff = async () => {
    setCopyBusy(true);
    try { await copyText(task.reply); await api('POST', `/tasks/${task.id}/complete`, { method: 'copied' }); await perform('GET', '/state'); notify('已复制审核后的回复。请在目标对话中检查后自行发送。'); }
    catch (e) { notify(`复制或记录失败：${(e as Error).message}`, true); }
    finally { setCopyBusy(false); }
  };
  return <><button className="back-link" onClick={() => navigate('tasks')}><ArrowLeft size={16} />返回任务中心</button><PageHead title={task.title} description={`${scenarios[task.scenario]} · ${task.sourceName || '手动输入'} · 创建于 ${formatTime(task.createdAt)}`} actions={<><Status status={task.status} />{task.status === 'archived' ? <Button variant="secondary" busy={busy} onClick={() => void perform('POST', `/tasks/${task.id}/restore`, {}, '任务已恢复')}><RotateCcw size={16} />恢复</Button> : <button className="icon-button" aria-label="归档任务" onClick={() => setConfirmArchive(true)}><Archive size={19} /></button>}</>} />
    <div className="task-progress">{[['理解内容', '01'], ['起草回复', '02'], ['人工审核', '03'], ['交接草稿', '04']].map(([label, number], i) => { const level = task.status === 'completed' ? 4 : task.status === 'approved' ? 3 : task.status === 'review' ? 2 : 1; return <div key={label} className={i < level ? 'progress-active' : ''}><span>{i < level - 1 ? <Check size={13} /> : number}</span>{label}{i < 3 && <ChevronRight size={15} />}</div>; })}</div>
    <div className="task-detail-grid"><div className="detail-source"><section className="panel detail-panel"><div className="panel-head"><h2><MessageSquare size={18} />任务上下文</h2><span className="subtle-badge">仅此任务</span></div><Field label="对话与任务说明"><textarea aria-label="任务上下文" rows={7} value={input} onChange={e => setInput(e.target.value)} maxLength={20000} disabled={readOnly} /></Field>{capture && <div className="capture-in-task"><span><ScanLine size={14} />本次截屏 · {capture.sourceName}</span><img src={capture.image} alt="待分析的窗口截图" /><small>截图仅在当前会话内保留，不写入备份。</small></div>}<div className="context-meta"><span>工作流程</span><strong>{workflow?.name || '通用回复助手'}</strong></div>{workflow && <p className="workflow-hint">{workflow.description}</p>}<div className="context-meta"><span>生成方式</span><div className="segmented"><button disabled={readOnly || busy} className={mode === 'demo' ? 'selected' : ''} onClick={() => setMode('demo')}>离线演示</button><button disabled={readOnly || busy} className={mode === 'live' ? 'selected' : ''} onClick={() => setMode('live')}>真实模型</button></div></div><div className={`mode-note ${mode === 'live' ? 'live' : ''}`}>{mode === 'demo' ? <><Zap size={16} /><span>使用规则示例演示流程，不进行视觉识别或模型调用。</span></> : <><Sparkles size={16} /><span>将任务与启用的业务知识发送至你配置的模型。{capture ? '本次还会发送上方截图。' : ''}</span></>}</div><Button className="full-width" disabled={readOnly || !input.trim()} busy={busy} onClick={() => mode === 'live' ? setConfirmLive(true) : void generate()}><Sparkles size={17} />{task.reply ? '重新起草回复' : '开始起草回复'}</Button></section>
      <section className="panel detail-panel knowledge-used"><h3><BookOpen size={16} />本次引用的知识</h3>{task.knowledgeIds.length ? task.knowledgeIds.map(id => { const item = state.knowledge.find(k => k.id === id); return <button key={id} onClick={() => navigate('knowledge')}><FileText size={15} /><span>{item?.title || '知识条目已删除'}</span><ArrowUpRight size={14} /></button>; }) : <p className="muted">起草后在这里显示匹配到的业务知识。</p>}</section></div>
      <section className="panel draft-panel"><div className="panel-head"><h2><Sparkles size={18} />回复草稿</h2><span className={`subtle-badge ${task.mode === 'demo' ? 'amber' : ''}`}>{task.mode === 'demo' ? '离线演示结果' : '真实模型结果'}</span></div>{task.reply || reply ? <><div className="draft-body"><label className="sr-only" htmlFor="reply">编辑回复草稿</label><textarea id="reply" value={reply} onChange={e => setReply(e.target.value)} disabled={readOnly} maxLength={20000} placeholder="在这里编辑需要发送的内容…" /><div className="draft-count">{reply.length} 字<span>{dirty ? '有未保存修改' : '已保存到本地'}</span></div>{task.rationale && <details className="rationale" open><summary><Circle size={11} />起草依据</summary><p>{task.rationale}</p></details>}</div><div className="draft-actions"><p><ShieldCheck size={15} />请检查事实、价格与承诺，确认后再交接。</p><div>{dirty && <Button variant="secondary" busy={busy} onClick={() => void save()}><Save size={16} />保存修改</Button>}{task.status === 'review' && !dirty && <Button busy={busy} disabled={!reply.trim()} onClick={() => void perform('POST', `/tasks/${task.id}/approve`, {}, '草稿已审核，可以交接')}><ShieldCheck size={17} />确认已审核</Button>}{task.status === 'approved' && !dirty && <><Button variant="secondary" busy={copyBusy} disabled={busy} onClick={() => void handoff()}><Copy size={16} />复制回复</Button>{window.flowdesk && capture?.sourceId.startsWith('window:') && <><Button disabled={!usbStatus?.connected} onClick={() => { setConfirmPaste(true); }}><ExternalLink size={16} />USB 逐键填入</Button></>}</>}{task.status === 'completed' && <span className="completed-note"><CheckCheck size={16} />草稿已交接，请自行确认发送结果</span>}</div></div></> : <Empty title="好的回复，从理解开始。" detail="检查左侧任务内容，点击起草。你可以先用离线演示体验完整流程。" />}</section>
    </div>
    {confirmLive && <Modal title="确认本次模型调用" subtitle="只发送这项任务需要的内容，调用可能产生供应商费用。" onClose={() => !busy && setConfirmLive(false)}><div className="transmission-list"><div><span>目标接口</span><code>{state.provider.baseUrl || '尚未配置'}</code></div><div><span>使用模型</span><strong>{state.provider.model || '尚未配置'}</strong></div><div><span>发送内容</span><strong>任务文字、工作流程、启用的知识{capture ? '、当前截图' : ''}</strong></div></div>{capture && <img className="confirm-screenshot" src={capture.image} alt="即将发给模型的截图" />}<p className="muted">请确认内容适合发送给以上服务商。生成后仍需人工审核。</p><div className="modal-actions"><Button variant="secondary" disabled={busy} onClick={() => setConfirmLive(false)}>取消</Button><Button busy={busy} onClick={() => void generate()}>确认并生成<ArrowUpRight size={16} /></Button></div></Modal>}
    {confirmPaste && capture && <Modal title="使用 USB 逐键填入审核后的回复" subtitle="Pico USB HID 逐键输入，不使用剪贴板或粘贴，不按回车，也不替你发送。" onClose={() => setConfirmPaste(false)}><div className="notice"><Monitor size={17} />目标：{capture.sourceName}</div><p className="muted">请先连接匹配固件的 Pico，使用全拼输入法并让目标输入框保持空白；候选词必须完整可见。若窗口、候选页、焦点或 USB 连接无法验证，操作会停止并保留草稿供人工清理。</p><blockquote className="reply-preview">{task.reply}</blockquote><div className="modal-actions"><Button variant="secondary" onClick={() => setConfirmPaste(false)}>取消</Button><Button busy={copyBusy} disabled={!usbStatus?.connected} onClick={async () => { setCopyBusy(true); try { const result = await window.flowdesk!.usb.pasteTask(task.id, capture.sourceId); if (!result.ok) throw new Error(result.message); await perform('GET', '/state'); notify(result.message); setConfirmPaste(false); } catch (e) { notify((e as Error).message, true); } finally { setCopyBusy(false); } }}>确认 USB 逐键填入</Button></div></Modal>}
    {confirmArchive && <Modal title="归档这个任务？" subtitle="任务和活动记录会保留，之后可以从已归档列表恢复。" onClose={() => setConfirmArchive(false)}><div className="modal-actions"><Button variant="secondary" onClick={() => setConfirmArchive(false)}>取消</Button><Button busy={busy} onClick={async () => { const result = await perform('POST', `/tasks/${task.id}/archive`, {}, '任务已归档'); if (result) setConfirmArchive(false); }}>归档任务</Button></div></Modal>}
  </>;
}
