param([switch]$Server,[switch]$Test)
$ErrorActionPreference='Stop'
function Fail($id) { @{ id=$id; ok=$false; protocol=4; device='FlowDesk USB Bridge'; firmware=''; board='pico'; armed=$false; session=''; leaseMs=0; error='usb_failed' } | ConvertTo-Json -Compress }
function New-FlowDeskSerial([string]$Port) { $s=[System.IO.Ports.SerialPort]::new($Port,115200,[System.IO.Ports.Parity]::None,8,[System.IO.Ports.StopBits]::One); $s.RtsEnable=$false; $s.ReadTimeout=100; $s.WriteTimeout=2000; $s.NewLine="`n"; return $s }
function Read-FlowDeskLine($Serial) { $bytes=[Collections.Generic.List[byte]]::new(); $deadline=[Diagnostics.Stopwatch]::StartNew(); while($deadline.ElapsedMilliseconds -lt 2000) { try { $n=$Serial.ReadByte() } catch { $timeout=$false; $cause=$_.Exception; while($cause) { if($cause -is [TimeoutException]){$timeout=$true;break}; $cause=$cause.InnerException }; if($timeout){continue}; throw }; if($n -eq 10) { return [Text.Encoding]::UTF8.GetString($bytes.ToArray()).TrimEnd("`r") }; if($n -lt 0) { continue }; if($bytes.Count -ge 4096) { throw 'oversize' }; $bytes.Add([byte]$n) }; throw 'timeout' }
function Invoke-FlowDeskRequest($Request,$Factory) { if($Request.port -notmatch '^COM([1-9]|[1-9][0-9]{1,3})$' -or [int]$Matches[1] -gt 9999 -or $Request.frame.Length -gt 160 -or $Request.frame -notmatch '^[\x20-\x7E\t]+$') { throw 'invalid' }; if(-not $script:Serial) { $script:Port=$Request.port.ToUpperInvariant(); $script:Serial=& $Factory $script:Port; $script:Serial.DtrEnable=$true; $script:Serial.Open() } elseif($script:Port -ne $Request.port.ToUpperInvariant()) { throw 'port_changed' }; $script:Serial.WriteLine($Request.frame); return Read-FlowDeskLine $script:Serial }
function Close-FlowDeskSerial { if($script:Serial) { try{$script:Serial.DtrEnable=$false}catch{}; try{$script:Serial.Close()}catch{}; try{$script:Serial.Dispose()}catch{}; $script:Serial=$null } }
function New-FakeSerial([byte[]]$Bytes,[string]$Failure='') { $fake=[pscustomobject]@{ DtrEnable=$false; RtsEnable=$false; Bytes=$Bytes; Index=0; Opens=0; Writes=0; Failure=$Failure }; Add-Member -InputObject $fake -MemberType ScriptMethod -Name Open -Value {$this.Opens++}; Add-Member -InputObject $fake -MemberType ScriptMethod -Name Close -Value {}; Add-Member -InputObject $fake -MemberType ScriptMethod -Name Dispose -Value {}; Add-Member -InputObject $fake -MemberType ScriptMethod -Name WriteLine -Value {param($x) $this.Writes++}; Add-Member -InputObject $fake -MemberType ScriptMethod -Name ReadByte -Value { if($this.Failure -eq 'disconnect'){throw [InvalidOperationException]::new('disconnected')}; if($this.Index -eq 0 -and $this.Failure -eq 'timeout-once'){$this.Index++;throw [TimeoutException]::new()}; $offset=if($this.Failure -eq 'timeout-once'){ $this.Index-1 }else{$this.Index}; if($offset -ge $this.Bytes.Length){throw [TimeoutException]::new()}; $this.Index++; return [int]$this.Bytes[$offset] }; return $fake }
function Invoke-UsbChannelTests { $script:Serial=$null; $script:Port=''; try { $fake=New-FakeSerial ([byte[]](65,66,10,67,10)) 'timeout-once'; $factory={param($p) $fake}; if((Invoke-FlowDeskRequest ([pscustomobject]@{port='COM1';frame='1`thello'}) $factory) -ne 'AB'){throw 'split read'}; if((Invoke-FlowDeskRequest ([pscustomobject]@{port='COM1';frame='2`tstatus'}) $factory) -ne 'C'){throw 'multi command'}; if($fake.Opens -ne 1 -or $fake.Writes -ne 2 -or -not $fake.DtrEnable -or $fake.RtsEnable){throw 'persistent open'}; try { Invoke-FlowDeskRequest ([pscustomobject]@{port='COM2';frame='3`thello'}) $factory; throw 'missing port change' } catch { if($_.Exception.Message -ne 'port_changed'){throw} }; Close-FlowDeskSerial; if($fake.DtrEnable){throw 'DTR not released'}; $script:Serial=$null; $oversize=New-FakeSerial ([byte[]](1..4097|%{65})); try { Invoke-FlowDeskRequest ([pscustomobject]@{port='COM1';frame='4`thello'}) {param($p)$oversize}; throw 'missing oversize' } catch { if($_.Exception.Message -ne 'oversize'){throw} }; Close-FlowDeskSerial; $script:Serial=$null; $broken=New-FakeSerial ([byte[]]@()) 'disconnect'; $watch=[Diagnostics.Stopwatch]::StartNew(); try { Invoke-FlowDeskRequest ([pscustomobject]@{port='COM1';frame='5`thello'}) {param($p)$broken}; throw 'missing disconnect' } catch { if($_.Exception.Message -notmatch 'disconnected'){throw} }; if($watch.ElapsedMilliseconds -gt 500){throw 'disconnect delayed'}; 'usb-channel-test-ok' } finally { Close-FlowDeskSerial } }
if($Test) { Invoke-UsbChannelTests; exit 0 }
if(-not $Server) { exit 1 }
$script:Serial=$null; $script:Port=''
try { while($line=[Console]::In.ReadLine()) { $id=$null; try { $request=$line|ConvertFrom-Json; $id=$request.id; [Console]::Out.WriteLine((Invoke-FlowDeskRequest $request ${function:New-FlowDeskSerial})) } catch { Close-FlowDeskSerial; [Console]::Out.WriteLine((Fail $id)) } } } finally { Close-FlowDeskSerial }
